### ISSUE TITLE
rosmake fails (stack.xml not allowed to have rosdeps) 

### ISSUE THREAD

**Issue by jamuraa** [CCNYRoboticsLab/ccny_rgbd_tools#20]
Using the groovy or the master branch, rosmake chokes on the rosdep entries in the stack.xml: 

<pre>
[ rosmake ] rosmake starting...                                                                                                
[ rosmake ] Packages requested are: ['ccny_rgbd_tools']                                                                        
[ rosmake ] Logging to directory /home/jamuraa/.ros/rosmake/rosmake_output-20130424-160259                                     
[ rosmake ] Expanded args ['ccny_rgbd_tools'] to:
['ccny_rgbd', 'ccny_rgbd_data', 'lib_rgbdtools', 'ccny_openni_launch', 'ccny_g2o']
Traceback (most recent call last):
  File "/opt/ros/groovy/bin/rosmake", line 55, in <module>
    if rma.main():
  File "/opt/ros/groovy/lib/python2.7/dist-packages/rosmake/engine.py", line 761, in main
    for d in rosstack.get_depends(s, implicit=False):
  File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 188, in get_depends
    m = self.get_manifest(name)
  File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 133, in get_manifest
    return self._load_manifest(name)
  File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 172, in _load_manifest
    retval = self._manifests[name] = parse_manifest_file(self.get_path(name), self._manifest_name)
  File "/usr/lib/pymodules/python2.7/rospkg/manifest.py", line 398, in parse_manifest_file
    return parse_manifest(manifest_name, f.read(), filename)
  File "/usr/lib/pymodules/python2.7/rospkg/manifest.py", line 468, in parse_manifest
    raise InvalidManifest("stack manifests are not allowed to have rosdeps")
InvalidManifest: stack manifests are not allowed to have rosdeps
Traceback (most recent call last):
  File "/opt/ros/groovy/bin/rosmake", line 55, in <module>
    if rma.main():
  File "/opt/ros/groovy/lib/python2.7/dist-packages/rosmake/engine.py", line 761, in main
    for d in rosstack.get_depends(s, implicit=False):
  File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 188, in get_depends
    m = self.get_manifest(name)
  File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 133, in get_manifest
    return self._load_manifest(name)
  File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 172, in _load_manifest
    retval = self._manifests[name] = parse_manifest_file(self.get_path(name), self._manifest_name)
  File "/usr/lib/pymodules/python2.7/rospkg/manifest.py", line 398, in parse_manifest_file
    return parse_manifest(manifest_name, f.read(), filename)
  File "/usr/lib/pymodules/python2.7/rospkg/manifest.py", line 468, in parse_manifest
    raise InvalidManifest("stack manifests are not allowed to have rosdeps") 
rospkg.manifest.InvalidManifest: stack manifests are not allowed to have rosdeps
</pre>

**Comment by ccny-ros-pkg** [comment]
Fixed in master.
